### ISSUE TITLE
Create Design Mockups in Figma

### ISSUE THREAD

**Issue by johnxlai** [johnxlai/travel-app#9]

**Comment by melissataylor1** [comment]
![Image](https://user-images.githubusercontent.com/122242449/216371356-9ea9b7cd-9f2b-4046-850b-5f72d1497216.png)
![Image](https://user-images.githubusercontent.com/122242449/216371357-2e82f679-bfe6-41af-b165-0839f157c2c5.png)
![Image](https://user-images.githubusercontent.com/122242449/216371358-3870eb69-1b33-4d51-9a64-2e634b209c3e.png)
